### ISSUE TITLE
The itr is 185.31 not 198.18

### ISSUE THREAD

**Issue by Sungden** [edwin465/SSVEP-stCCA#1]
![image](https://user-images.githubusercontent.com/54644867/234795698-5327169e-be35-4aaf-b889-46411f69de6a.png)

Using your code, the itr is 185.31, which is a little lower than the report's. What is the wrong ?
Thanks!

**Comment by edwin465** [comment]
After checking the source code, I found that the latency parameter in the code 'fun_calculate_ssvep_template.m' should be changed from 0.13 to 0.14. 
In line 11, latencyDelay = 0.13; 

The reason is that the latency should be consistent with the one in the code 'fun_stcca.m'
In line 15: latencyDelay=0.14;

Finally, we can obtain the same ITR (198.18 bpm) as shown in the paper.

**Comment by Sungden** [comment]
Thanks, I got the same results now.
