### ISSUE TITLE
about the effect of Nsub

### ISSUE THREAD

**Issue by Sungden** [edwin465/SSVEP-stCCA#2]
Dear author, in Figure 5 of your paper, you presented the number of source subjects has little effect on the performance when it >5.
<img width="398" alt="image" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/4f29aee5-704c-45bf-91b3-40094450d500">

But when I reproduced your code and set the number of source subjects to 9, I got a worse result below.
<img width="248" alt="image" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/2f894afc-202d-4485-9f2b-da05d784d357">. In my experiments, I just randomly selected 10 subjects and repeated the experiment in different subjects. I wonder if there is any mistake in my experiments.

Thanks!

**Comment by edwin465** [comment]
Dear Sungden,

Thanks for your email. The results in Figure 5 are the average results. For
example, the sub-figures in the right side are not obtained based on one
specified TW, subject group, and N_{trial}.
Hence, it is hard for us to determine whether the results you showed in the
email (i.e. using only 10 subjects, TW=0.6s) are in line with my results or
not.

Actually, I am not sure whether our evaluation scheme is similar to yours
or not. Our evaluation scheme is that I selected several source subjects
(e.g., 5, 10, 15, ...) randomly from 34 subjects (excluding the target
subject) for the target subject to do the calculation. Then, we could get
35 results corresponding to 35 target subjects under the
specified parameters. Eventually, we averaged all the results across
different parameters and plotted Figure 5. I guess that we used two
different evaluation schemes, so that the final results are not consistent.

============================================================================================================
In order to check whether our github code has bug or not,  I tested it
again.
At first, I ran the following code, and we could get the result of 198.18
bpm.

fun_calculate_ssvep_template(1); % run it if you do not have
'th_ssvep_template_for_stcca.mat'
k=9; tw=0.7;
f_idx=round((40/k*[1:k]+40/k*[0:k-1])/2);
[sub_acc]=fun_stcca(f_idx,1,tw,1);
all_sub_itr=itr_bci(sub_acc/100,40,(tw+0.5)*ones(35,1));
mean(all_sub_itr);

Second, I tried to modified some code (highlighted in red color) in the
fun_stcca() so that it could randomly select *10 source subjects* for the
learning.
if run==1
   source_idx=sub_idx;
   source_idx(sn)=[];
   r_idx=randperm(length(source_idx));
   source_idx=source_idx(r_idx(1:10));
end
source_ssvep_temp0=zeros(length(source_idx),temp_len*length(f_idx));

source_ssvep_temp=zeros(1,d4);

Then we could get the result of ~ 192 bpm. (several testing results are
around 192 bpm with small standard deviation)

Third, I tried to modified to randomly select *5 source subjects* for the
learning in the fun_stcca(), and finally could get the result of ~187 bpm.

I repeated the evaluation several times. I found that the standard
deviation is small for different number of source subjects.
============================================================================================================

*You mentioned that the results are not good. Based on my understanding,
maybe it is caused by *
*1) Smaller subject number in your evaluation (10 subjects in your
evaluation while 35 subjects in our evaluation)*.
*2) Smaller variations in source subject pool for transfer learning in your
evaluation (i.e., every target subject uses the similar source subjects for
transferl learning). *

Best regards,
Chi Man Wong




Sungden ***@***.***> 於 2023年8月30日 週三 下午5:33寫道：

**Comment by Sungden** [comment]
Thank you for your patient and meticulous response！
