### ISSUE TITLE
Why using sort in line 8 of fun_calculate_ssvep_template.m and line 12 of fun_stcca.m

### ISSUE THREAD

**Issue by Sungden** [edwin465/SSVEP-stCCA#4]
Dr. Wong, why do you use sort in line 8 of fun_calculate_ssvep_template.m and line 12 of fun_stcca.m? When I change this setting to 1-40 to keep the original order of stimulus frequency. The result is much lower (0.7385 VS. 0.4156 for 0.5s SSVEP).
<img width="476" alt="1701263156474" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/c5ff785a-f3d1-4bfa-a728-20c3d01bea82">

<img width="277" alt="1701263219499" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/ff421328-38d0-487f-8a2f-60f4ed97689f">

**Comment by edwin465** [comment]
The key reason is to sort the 'frequency' order of the dataset. The original frequency order is 8.0, 9.0, ..., 15.0, 8.2, 9.2, ..., 15.2, 8.4, 9.4, ..., 15.4, 8.6, 9.6, ..., 15.6, 8.8, 9.8, ..., 15.8 (as the variable **sti_f** defined). After the sorting, the new frequency order should be 8.0, 8.2, 8.4, 8.6, 8.8, ..., 15.8. 

When you change the setting, you should also pre-define the **pha_val** because the current **pha_val** is designed for the new frequency order 8.0, 8.2, 8.4, 8.6, 8.8, ..., 15.8. In the stCCA, the sine-cosine reference signals are designed with the specified frequencies and phases. If the phase is not correctly designed, the resulting performance would be degraded.

Please check if my guess is correct or not. Let me know if you have any problem. Thank you!

**Comment by Sungden** [comment]
But the original phases should be 0,0.5,1,1.5,... and correspond with the original frequencies 8.0, 9.0, ..., 15.0, 8.2, 9.2, ..., 15.2, 8.4, 9.4, ..., 15.4, 8.6, 9.6, ..., 15.6, 8.8, 9.8, ..., 15.8. If you sort the frequency, their correspondence has been broken.

<img width="312" alt="1701317018124" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/ca0a9b79-a622-4492-938a-208687832ae6">
<img width="438" alt="1701316969168" src="https://github.com/edwin465/SSVEP-stCCA/assets/54644867/f07c3ead-3772-4c08-9887-efcc9401d81c">

**Comment by edwin465** [comment]
The original phases are not 
[0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, ...
 0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, ...
 0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, ...
 0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, ...
 0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi]. 

According to the figure you provided, the original phases are
[0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, ...
 **0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi, 0 ...
1pi,1.5pi,0,0.5pi,1pi,1.5pi, 0, 0.5pi ...
1.5pi,0,0.5pi,1pi,1.5pi, 0,0.5pi,1pi  ...**
 0,0.5pi,1pi,1.5pi,0,0.5pi,1pi,1.5pi]. 

Note that not all phase difference is 0.5pi. For example, the phase difference between the 8th phase and the 9th phase is not equal to 0.5pi. 

Therefore, when you change the setting in **target_order**, you should also pre-define the **pha_val**.
